# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Code for creating a build
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    # Setup/Install Node js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #Install project dependencies
    - name: Install Dependencies
      run: npm install 
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  # Code for deploying the project on Heroku
  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
    - uses: actions/checkout@v3 # Checkout latest code
    - uses: PrateekBalhara/CSD4553_CICDpipeline # Name of the repository
      with:
        #Heroku api key. I haved stored it in secrets with name as "HEROKU_API_KEY"
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} 
        heroku_app_name: "csd4553" #App name from Heroku
        heroku_email: "c0830002@mylambton.ca" # Your email id from Heroku Account

